name: KC CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/kc-kube-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/kc-kube-app:latest

    - name: Deploy to Kubernetes
      env:
        INSTANCE_PUBLIC_IP: ${{ secrets.INSTANCE_PUBLIC_IP }}
        SSH_PEM_KEY: ${{ secrets.SSH_PEM_KEY }}
      run: |
        echo "${SSH_PEM_KEY}" > ssh_key_pair.pem
        chmod 600 ssh_key_pair.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key_pair.pem ubuntu@${EC2_PUBLIC_IP} << "EOF"
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
        EOF
